name: 'dbt_snowflake_gcp'
version: '1.0.0'
config-version: 2

profile: 'dbt_snowflake_gcp'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_snowflake_gcp:
    +schema: raw

models:
  dbt_snowflake_gcp:
    demo:
      +materialized: table
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
      ephemeral:
        +materialized: ephemeral
